// linuxity/vfs/procfs.hpp
//
// A synthesized /proc — the virtual window onto linuxity's own world.
//
// /proc is not a disk filesystem; every file is produced on demand by the
// kernel from live state. We mirror that: a producer function maps an
// absolute /proc path to freshly generated bytes. Programs poke /proc very
// early (glibc reads /proc/self/... , shells read /proc/mounts, coreutils
// read /proc/filesystems), so having it return linuxity's numbers instead of
// the host's is what keeps the guest inside our world.
//
// This is deliberately a plain producer (not a FileSystem backend): the
// syscall path only needs "give me the bytes of this virtual path", and a
// closure over the kernel is the most direct expression of that.
#pragma once

#include "linuxity/kernel/file_namespace.hpp"

#include <string>
#include <string_view>

namespace lx::vfs {

// Build a /proc producer bound to linuxity's identity (pid, uname release).
[[nodiscard]] inline kernel::FileNamespace::Producer
make_procfs(int self_pid, std::string release, std::string nodename) {
    return [self_pid, release = std::move(release),
            nodename = std::move(nodename)]
           (std::string_view abs) -> Result<kernel::VirtualFile> {
        auto text = [](std::string s) {
            kernel::VirtualFile vf;
            vf.bytes.resize(s.size());
            for (std::size_t i = 0; i < s.size(); ++i)
                vf.bytes[i] = static_cast<std::byte>(s[i]);
            return ok(vf);
        };
        auto dir = []() {
            kernel::VirtualFile vf; vf.is_dir = true; return ok(vf);
        };
        const std::string self = "/proc/" + std::to_string(self_pid);

        // Normalize /proc/self -> /proc/<pid> so both spellings resolve.
        std::string p{abs};
        if (p == "/proc/self" || p.starts_with("/proc/self/"))
            p = self + p.substr(std::string_view{"/proc/self"}.size());

        if (abs == "/proc" || abs == "/proc/self" || p == self) return dir();

        if (p == self + "/cmdline")  return text(std::string("linuxity\0", 9));
        if (p == self + "/comm")     return text("linuxity\n");
        if (p == self + "/stat")
            return text(std::to_string(self_pid) + " (linuxity) R 0 " +
                        std::to_string(self_pid) + " " +
                        std::to_string(self_pid) + " 0 -1 0 0 0 0 0 0 0 0 0 "
                        "20 0 1 0 0 0 0\n");
        if (p == self + "/status")
            return text("Name:\tlinuxity\nState:\tR (running)\nPid:\t" +
                        std::to_string(self_pid) + "\nPPid:\t0\n"
                        "Uid:\t0\t0\t0\t0\nGid:\t0\t0\t0\t0\n");

        if (abs == "/proc/version")
            return text("Linux version " + release +
                        " (linuxity@" + nodename +
                        ") (linuxity portable Linux ABI)\n");
        if (abs == "/proc/cpuinfo")
            return text("processor\t: 0\nvendor_id\t: LinuxityVirtual\n"
                        "model name\t: linuxity native CPU\nflags\t\t: fpu\n\n");
        if (abs == "/proc/meminfo")
            return text("MemTotal:        2097152 kB\nMemFree:         1048576 kB\n"
                        "MemAvailable:    1572864 kB\n");
        if (abs == "/proc/mounts" || abs == "/proc/self/mounts")
            return text("rootfs / rootfs rw 0 0\nproc /proc proc rw 0 0\n"
                        "tmpfs /tmp tmpfs rw 0 0\n");
        if (abs == "/proc/filesystems")
            return text("nodev\tproc\nnodev\ttmpfs\n\text4\n");
        if (abs == "/proc/uptime")   return text("100.00 100.00\n");
        if (abs == "/proc/loadavg")  return text("0.00 0.00 0.00 1/1 " +
                                                  std::to_string(self_pid) + "\n");
        if (abs == "/proc/sys/kernel/osrelease") return text(release + "\n");
        if (abs == "/proc/sys/kernel/hostname")  return text(nodename + "\n");

        return err<kernel::VirtualFile>(Errno::enoent);
    };
}

} // namespace lx::vfs
